name: node-test

services:
    db:
        image: postgres:17.5-alpine
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - app-data:/var/lib/postgresql/data
        networks:
            - app-network

    app:
        build: .
        environment:
            - PORT=3000
            - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
        ports:
            - 3000:3000
        networks:
            - app-network

volumes:
    app-data:

networks:
    app-network:
