name: node-test

services:
    db:
        image: postgres:17.5-alpine
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        volumes:
            - app-data:/var/lib/postgresql/data
        networks:
            - app-network

    app:
        build: .
        environment:
            - PORT=3000
            - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
        ports:
            - 3000:3000
        volumes:
            - ./src:/app/src
        networks:
            - app-network

volumes:
    app-data:

networks:
    app-network:
